"""initial GrokIQ schema

Revision ID: 8953b4278bf6
Revises:
Create Date: 2026-08-09 16:15:56.742848
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "8953b4278bf6"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_assessments",
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("monitor_status", sa.String(length=24), nullable=False),
        sa.Column("risk_score", sa.Float(), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column("anomaly_count", sa.Integer(), nullable=False),
        sa.Column("hard_anomaly_count", sa.Integer(), nullable=False),
        sa.Column("fast_risk_count", sa.Integer(), nullable=False),
        sa.Column("marker_miss_count", sa.Integer(), nullable=False),
        sa.Column("distinct_egress_count", sa.Integer(), nullable=False),
        sa.Column("anomaly_streak", sa.Integer(), nullable=False),
        sa.Column("avg_tps", sa.Float(), nullable=False),
        sa.Column("max_tps", sa.Float(), nullable=False),
        sa.Column("latest_tps", sa.Float(), nullable=False),
        sa.Column("latest_classification", sa.String(length=32), nullable=False),
        sa.Column("latest_sample_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_anomaly_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("risk_reasons", sa.JSON(), nullable=False),
        sa.Column("quarantine_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("disabled_by_monitor", sa.Boolean(), nullable=False),
        sa.Column("previous_upstream_enabled", sa.Boolean(), nullable=True),
        sa.Column("manual_note", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("account_id"),
    )
    op.create_index(
        op.f("ix_account_assessments_monitor_status"), "account_assessments", ["monitor_status"], unique=False
    )
    op.create_index(
        op.f("ix_account_assessments_quarantine_until"),
        "account_assessments",
        ["quarantine_until"],
        unique=False,
    )
    op.create_index(
        op.f("ix_account_assessments_risk_score"), "account_assessments", ["risk_score"], unique=False
    )
    op.create_table(
        "alerts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=48), nullable=False),
        sa.Column("severity", sa.String(length=24), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("acknowledged", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alerts_account_id"), "alerts", ["account_id"], unique=False)
    op.create_index(op.f("ix_alerts_created_at"), "alerts", ["created_at"], unique=False)
    op.create_table(
        "app_settings",
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "metadata",
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "probe_profiles",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("model", sa.String(length=160), nullable=False),
        sa.Column("system_prompt", sa.Text(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("expected_text", sa.String(length=2000), nullable=False),
        sa.Column("expected_image_url", sa.String(length=4000), nullable=False),
        sa.Column("max_output_tokens", sa.Integer(), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=True),
        sa.Column("extra_body", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "schedule_executions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("schedule_key", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("message", sa.String(length=500), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_schedule_execution_key_started",
        "schedule_executions",
        ["schedule_key", "started_at"],
        unique=False,
    )
    op.create_index(op.f("ix_schedule_executions_status"), "schedule_executions", ["status"], unique=False)
    op.create_table(
        "probe_plans",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("profile_id", sa.String(length=64), nullable=False),
        sa.Column("account_ids", sa.JSON(), nullable=False),
        sa.Column("proxy_targets", sa.JSON(), nullable=False),
        sa.Column("rounds", sa.Integer(), nullable=False),
        sa.Column("cron_expression", sa.String(length=120), nullable=False),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("overlap_policy", sa.String(length=16), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["probe_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_probe_plans_enabled"), "probe_plans", ["enabled"], unique=False)
    op.create_table(
        "probe_runs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("account_name", sa.String(length=160), nullable=False),
        sa.Column("account_email", sa.String(length=255), nullable=False),
        sa.Column("profile_id", sa.String(length=64), nullable=False),
        sa.Column("plan_id", sa.String(length=64), nullable=True),
        sa.Column("parent_run_id", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("trigger", sa.String(length=24), nullable=False),
        sa.Column("automatic", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("rounds", sa.Integer(), nullable=False),
        sa.Column("proxy_targets", sa.JSON(), nullable=False),
        sa.Column("total_steps", sa.Integer(), nullable=False),
        sa.Column("completed_steps", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("current_round", sa.Integer(), nullable=True),
        sa.Column("current_target_key", sa.String(length=100), nullable=True),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("worker_id", sa.String(length=100), nullable=True),
        sa.Column("summary", sa.JSON(), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("original_egress_node_id", sa.Integer(), nullable=True),
        sa.Column("original_egress_assignment_mode", sa.String(length=16), nullable=False),
        sa.Column("temporary_route_id", sa.String(length=64), nullable=False),
        sa.Column("temporary_public_model", sa.String(length=255), nullable=False),
        sa.Column("temporary_client_key_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("queued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["parent_run_id"], ["probe_runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["plan_id"], ["probe_plans.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["probe_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_probe_run_account_created", "probe_runs", ["account_id", "created_at"], unique=False)
    op.create_index(
        "ix_probe_run_status_priority", "probe_runs", ["status", "priority", "created_at"], unique=False
    )
    op.create_index(op.f("ix_probe_runs_account_id"), "probe_runs", ["account_id"], unique=False)
    op.create_index(op.f("ix_probe_runs_plan_id"), "probe_runs", ["plan_id"], unique=False)
    op.create_index(op.f("ix_probe_runs_status"), "probe_runs", ["status"], unique=False)
    op.create_table(
        "probe_samples",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column("target_key", sa.String(length=100), nullable=False),
        sa.Column("target_kind", sa.String(length=16), nullable=False),
        sa.Column("egress_node_id", sa.Integer(), nullable=True),
        sa.Column("egress_name", sa.String(length=160), nullable=False),
        sa.Column("request_id", sa.String(length=100), nullable=False),
        sa.Column("audit_id", sa.Integer(), nullable=True),
        sa.Column("verified_account_id", sa.Integer(), nullable=True),
        sa.Column("verified_egress_node_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("reasoning_tokens", sa.Integer(), nullable=False),
        sa.Column("visible_tokens", sa.Integer(), nullable=False),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("first_token_ms", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("generation_ms", sa.Integer(), nullable=False),
        sa.Column("first_token_share", sa.Float(), nullable=False),
        sa.Column("tps", sa.Float(), nullable=False),
        sa.Column("expected_matched", sa.Boolean(), nullable=True),
        sa.Column("response_sha256", sa.String(length=128), nullable=False),
        sa.Column("response_text", sa.Text(), nullable=False),
        sa.Column("usage", sa.JSON(), nullable=False),
        sa.Column("classification", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["probe_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "round_number", "target_key", name="uq_probe_step"),
    )
    op.create_index(
        "ix_probe_sample_account_created", "probe_samples", ["account_id", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_probe_samples_classification"), "probe_samples", ["classification"], unique=False
    )
    op.create_index(op.f("ix_probe_samples_run_id"), "probe_samples", ["run_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_probe_samples_run_id"), table_name="probe_samples")
    op.drop_index(op.f("ix_probe_samples_classification"), table_name="probe_samples")
    op.drop_index("ix_probe_sample_account_created", table_name="probe_samples")
    op.drop_table("probe_samples")
    op.drop_index(op.f("ix_probe_runs_status"), table_name="probe_runs")
    op.drop_index(op.f("ix_probe_runs_plan_id"), table_name="probe_runs")
    op.drop_index(op.f("ix_probe_runs_account_id"), table_name="probe_runs")
    op.drop_index("ix_probe_run_status_priority", table_name="probe_runs")
    op.drop_index("ix_probe_run_account_created", table_name="probe_runs")
    op.drop_table("probe_runs")
    op.drop_index(op.f("ix_probe_plans_enabled"), table_name="probe_plans")
    op.drop_table("probe_plans")
    op.drop_index(op.f("ix_schedule_executions_status"), table_name="schedule_executions")
    op.drop_index("ix_schedule_execution_key_started", table_name="schedule_executions")
    op.drop_table("schedule_executions")
    op.drop_table("probe_profiles")
    op.drop_table("metadata")
    op.drop_table("app_settings")
    op.drop_index(op.f("ix_alerts_created_at"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_account_id"), table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(op.f("ix_account_assessments_risk_score"), table_name="account_assessments")
    op.drop_index(op.f("ix_account_assessments_quarantine_until"), table_name="account_assessments")
    op.drop_index(op.f("ix_account_assessments_monitor_status"), table_name="account_assessments")
    op.drop_table("account_assessments")
    # ### end Alembic commands ###
